# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13z1dJojjyPL1BoqQBYgB0Q6qKUzbBLup
"""

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import joblib
import pandas as pd


app = FastAPI()


class InputData(BaseModel):
    Time: float
    Income: float
    Created_at: str  # input date string in 'YYYY-MM-DD HH:MM:SS' format

# Load the saved model
model = joblib.load('balanced_bagging_model.joblib')


@app.post("/predict/")
def predict(data: InputData):
    try:

        input_df = pd.DataFrame([data.dict()])
        input_df['Created_at'] = pd.to_datetime(input_df['Created_at'])
        input_df['Month'] = input_df['Created_at'].dt.month
        input_df['Day'] = input_df['Created_at'].dt.day
        input_df['Hour'] = input_df['Created_at'].dt.hour
        input_df = input_df.drop('Created_at', axis=1)


        prediction = model.predict(input_df)
        probability = model.predict_proba(input_df)[:, 1]  # Probability of class 1


        return {"prediction": int(prediction[0]), "probability": float(probability[0])}

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))