# -*- coding: utf-8 -*-
"""eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13z1dJojjyPL1BoqQBYgB0Q6qKUzbBLup
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

#loading data
train_df = pd.read_csv('task_train.csv')
test_df = pd.read_csv('task_test.csv')

#drop columns###################
cols_to_drop = ['Unnamed: 0.1', 'Unnamed: 0','ID', 'UserID', 'Created_at', 'Origin', 'Destination', 'Comment']
X_train = train_df.drop(cols_to_drop, axis=1)
X_test = test_df.drop(cols_to_drop, axis=1)
y_train = train_df['Label']
y_test = test_df['Label']

# label distribution #################
plt.figure(figsize=(8, 5))
sns.countplot(x='Label', data=train_df)
plt.title('Distribution of Target Variable')
plt.show()

# features summary#################
print("Numeric features summary:")
print(X_train.describe())

# Correlation matrix#############
plt.figure(figsize=(10, 8))
sns.heatmap(X_train.corr(), annot=True, cmap='coolwarm', vmin=-1, vmax=1)
plt.title('Correlation Matrix')
plt.show()

########missing values #############
print("Missing values summary:")
print(X_train.isnull().sum())

########boxplot###########
plt.figure(figsize=(10, 6))
sns.boxplot(data=X_train[['Time', 'Income']])
plt.title('Boxplot for Numeric Features')
plt.show()